### PR TITLE
Test against same repos as standard

### PR DESCRIPTION
**Pull request by josephfrazier**
Hey @Flet, I happened across the project while doing some research for a
similar one of my own: https://github.com/josephfrazier/standard-eject

After trying out standardx, it seems to have fewer bugs than
standard-eject, so I'm considering rewriting standard-eject to use
standardx instead of eslint directly. Along the way, I thought I'd write
some tests for standardx, to help iron out any remaining compatibility
issues.

This replaces test/index.js with test/clone.js, copied from
https://github.com/standard/standard/blob/dc5d1dacda93de1f7fdd91fc53b75d013bad3f4b/test/clone.js

Here's some of the test output, showing which repositories currently
fail:

    Failed Tests: There were 17 failures

      test github repos that use `standard`

        ✖ helmet (https://github.com/helmetjs/helmet)
        ✖ buffer (https://github.com/feross/buffer)
        ✖ proxyquire-universal (https://github.com/bendrucker/proxyquire-universal)
        ✖ standard-format (https://github.com/maxogden/standard-format)
        ✖ humanize-duration (https://github.com/EvanHahn/HumanizeDuration.js)
        ✖ create-torrent (https://github.com/feross/create-torrent)
        ✖ builtin-status-codes (https://github.com/bendrucker/builtin-status-codes)
        ✖ electron-spawn (https://github.com/maxogden/electron-spawn)
        ✖ error-system (https://github.com/fanatid/error-system)
        ✖ express-restify-mongoose (https://github.com/florianholzapfel/express-restify-mongoose)
        ✖ js-data-adapter-tests (https://github.com/js-data/js-data-adapter-tests)
        ✖ reeal (https://github.com/reg4in/reeal)
        ✖ get-installed-path (https://github.com/tunnckoCore/get-installed-path)
        ✖ compose-editor (https://github.com/lucthev/compose)
        ✖ raml-client-generator (https://github.com/mulesoft/raml-client-generator)
        ✖ tape-promise (https://github.com/jprichardson/tape-promise)
        ✖ semistandard-format (https://github.com/ricardofbarros/semistandard-format)

    total:     228
    passing:   211
    failing:   17
    duration:  1m 23.3s

### CODE REVIEW

**Comment by josephfrazier** [comment]
It looks like most of these failures happen on repositories that use the "standard" key in package.json to specify additional options. Since [standardx specifies that its command is `standardx`](https://github.com/standard/standardx/blob/bd4211d835e0d99e51b35f17fb74ef0d3586b46f/options.js#L7), standard-engine [attempts to read](https://github.com/standard/standard-engine/blob/4dab2dd587815eed36185f6294194b19ae41d313/index.js#L132) the "standardx" key of package.json instead of "standard".

We could fix this in standard-engine by allowing a new property on [`opts`](https://github.com/standard/standard-engine/blob/4dab2dd587815eed36185f6294194b19ae41d313/index.js#L25) to override `opts.cmd` for the purposes of reading package.json. As a workaround, standardx could set `opts.cmd` to "standard", which would cause the package.json to be read correctly, but would make the `standardx --help` message misleading, etc.

**Comment by Flet** [comment]
Hi @josephfrazier!

I'd rather keep the key in "package.json" as `standardx` and I'd rather not automatically include checking the `standard` key as that could cause weird behavior for folks.

Another workaround would be to modify the `package.json` files of the cloned test repositories to use `standardx` instead.

All this being said, I think testing the main behavior of overriding eslint rules via `.eslintrc` and/or `package.json` could be more beneficial.

**Comment by josephfrazier** [comment]
> I'd rather keep the key in "package.json" as standardx and I'd rather not automatically include checking the standard key as that could cause weird behavior for folks.

That makes sense, I see the benefit of keeping things explicit.

> Another workaround would be to modify the package.json files of the cloned test repositories to use standardx instead.

For what it's worth, I've rewritten `standard-eject` to do this: https://github.com/josephfrazier/standard-eject/blob/82953fdbc83bc203fc41ba2d0450c6d091652b08/bin/standard-eject#L54-L67

I also just added a commit here that does the same, if you're still interested in the idea.

> All this being said, I think testing the main behavior of overriding eslint rules via .eslintrc and/or package.json could be more beneficial.

Hmm yeah, I can see how testing the friction of migrating from standard to standardx could be considered outside the goals of the project. Maybe we should add a note to the README about the package.json key name?

**Comment by josephfrazier** [comment]
> I can see how testing the friction of migrating from standard to standardx could be considered outside the goals of the project.

I'll go ahead and close this, due to the above. Note that standard-eject has the same tests, so if those start failing, I should be able to report any underlying standardx issue here :)

**Pull request closed without merging**
