### PR TITLE
Update to Standard 17

### LINKED ISSUE #41: Allow Standard 17
**What version of this package are you using?**
7.0.0

**What problem do you want to solve?**
Add Standard 17 compatibility

**What do you think is the correct solution to this problem?**
Allow Standard 17 in package.json

**Are you willing to submit a pull request to implement this change?**
Yes, but as a non-javascript developer I'm not confident

### PR DESCRIPTION
**Pull request by tagliala**
Close #41

**What is the purpose of this pull request? (put an "X" next to item)**
Allows use of Standard Engine 15 and Standard 17

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Simple PR

**Which issue (if any) does this pull request address?**
#41 

**Is there anything you'd like reviewers to focus on?**
Everything, I'm not a javascript developer

### CODE REVIEW

**Review by tomaswarynyca — APPROVED** [review]
LGTM! :rocket:

**Comment by jankapunkt** [comment]
@feross is there something preventing to merge and publish this one?

**Comment by tagliala** [comment]
@jankapunkt yes, there is actually an issue with snazzy and an upstream dependency not supporting warning messages

Refs:
- standard/eslint-config-standard#229
- standard/snazzy#29

**Comment by xChickens** [comment]
Any update regarding being able to fix the block in Snazzy? I wanted to use the newest version of the eslint-config-standard-with-typescript since the latest versions of typescript aren't officially supported, but standardx cause version conflicts since the config uses Standard 17, while standardx is still stuck on 16.

**Comment by tagliala** [comment]
As a non javascript developer, during my brief investigation, I was not able to understand where the parsing happen, so the problem may not be in Snazzy only. Ref: https://github.com/standard/snazzy/issues/29#issue-1259644824

**Comment by tagliala** [comment]
Moving to eslint, thanks for all these years

**Pull request closed without merging**
