### PR TITLE
update to esm

### LINKED ISSUE #39: Usage of ESM imports instead of CommonJS
We should use ESM imports instead of CommonJS.
See: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

It would offer a smoother transition when `standard-engine` has been migrated completely to ESM, see: https://github.com/standard/standard-engine/issues/251.

### PR DESCRIPTION
**Pull request by jimmywarting**
You know the drill now...
- same cli.js stuff as the rest
- same engine.node
- also switched travis to gh workflow 

closes #39

### CODE REVIEW

**Comment by theoludwig** [comment]
Hey! :wave: @jimmywarting 

Thanks again for this PR. :smile:
Could you change the CI from Travis to GitHub Actions, that could be in separated PR but to make things simple, we can do it in this PR, so we can have CI checks (it seems like Travis is not running).

Here are the steps:
- copy/paste `.github/workflows/test.yml` and `.github/workflows/old-test.yml` from [semistandard](https://github.com/standard/semistandard)
- remove `.travis.yml` file
- update the badges in `README.md` :
```md
[tests-image]: https://github.com/standard/standardx/actions/workflows/test.yml/badge.svg
[tests-url]: https://github.com/standard/standardx/actions/workflows/test.yml
```

**Comment by jimmywarting** [comment]
Thanks for the steps, i implemented it

**Review by theoludwig — APPROVED** [review]
LGTM! :+1:

Somehow, the CI is not running for some reasons, will need to investigate how to run it.

**Review by voxpelli — APPROVED** [review]
We should maybe look at starting to use [ghat](https://github.com/fregante/ghat) and have a `standard/ghatemplates` like my https://github.com/voxpelli/ghatemplates

That way we wouldn't need to manually copy and paste the actions inbetween the repos, we could simply run `ghat` to pull in the latest desired version.

But for now: LGTM 👍 Hopefully the actions will start running post merge

**Pull request merged**
